version: '3.8'
services:
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "${PMA_PORT}:80"
        networks:
            mynetwork:
                ipv4_address: ${PMA_HOST_IP}
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            mynetwork:
                ipv4_address: ${MYSQL_HOST_IP}
        volumes:
            - "${MYSQL_DB_FILES}:/var/lib/mysql"
            - "${MY_CNF_CONFIG}:/etc/mysql/${MY_CNF_CONFIG}"


networks:
    mynetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
