version: '3.8'
services:
    web:
        image: nginx
        volumes:
            - "./etc/nginx/conf.d:/etc/nginx/conf.d"
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "${PROJECT_DIR}:/var/www/html"
        ports:
            - "8000:80"
            - "3000:443"
        networks:
            mynetwork:
                ipv4_address: ${NGINX_HOST}
        # environment:
        #     - NGINX_HOST=${NGINX_HOST}
        # command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: ./etc/php/Dockerfile
        networks:
            mynetwork:
                ipv4_address: ${PHP_HOST_IP}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            # - "${PROJECT_DIR}:/var/www/html"
    composer:
        image: "composer"
        volumes:
            - "${PROJECT_DIR}:/var/www/html"
        command: composer install --ignore-platform-reqs

networks:
    mynetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}


